trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  adoProjectName: 'demo-project-name-2'
  adoOrganizationUri: 'https://dev.azure.com/scrutz'
  resourceGroupName: 'demo-project-rg'
steps:

- task: CmdLine@2
  inputs:
    script: 'curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash'
    
- task: CmdLine@2
  inputs:
    script: 'echo  $(PAT) | az devops login --organization https://dev.azure.com/scrutz/'   

- task: Bash@3
  inputs:
    targetType: filepath
    filepath: 'create-project.sh'
    arguments: '$(adoProjectName) $(adoOrganizationUri)'
