trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  adoProjectName: 'demo-project-name-2'
  adoOrganizationUri: 'https://dev.azure.com/scrutz'
  resourceGroupName: 'demo-project-rg'
steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      'curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      'echo  $(PAT) | az devops login --organization https://dev.azure.com/scrutz/'

- task: Bash@3
  inputs:
    targetType: filepath
    filepath: 'create-project.sh'
    arguments: '$(adoProjectName) $(adoOrganizationUri)'
