trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  adoProjectName: 'demo-project-name1'
  adoOrganizationUri: 'https://dev.azure.com/scrutz'
steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      ls
      
- task: AzureCLI@2
  displayName: Azure CLI
  inputs:
    azureSubscription: 'Demo Account MSDN'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: 'create-project.sh'
    arguments: '$(adoProjectName) $(adoOrganizationUri)'

- task: AzureCLI@2
  displayName: Azure CLI
  inputs:
    azureSubscription: 'Demo Account MSDN'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: 'create-project.sh'
    arguments: '$(adoProjectName) $(adoOrganizationUri)'
    
