trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  adoProjectName: 'demo-project-name6'
  adoOrganizationUri: 'https://dev.azure.com/scrutz'
  resourceGroupName: 'demo-project-rg'
steps:
- task: JavaToolInstaller@0
    inputs:
      versionSpec: "11"
      jdkArchitectureOption: x64
      jdkSourceOption: LocalDirectory
      jdkFile: "/builds/openjdk-11.0.2_linux-x64_bin.tar.gz"
      jdkDestinationDirectory: "/builds/binaries/externals"
      cleanDestinationDirectory: true
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      ls

- task: AzureCLI@2
  displayName: Azure CLI
  inputs:
    azureSubscription: 'Demo Account'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'echo  $(PAT) | az devops login --organization https://dev.azure.com/scrutz/'

- task: AzureCLI@2
  displayName: Azure CLI
  inputs:
    azureSubscription: 'Demo Account MSDN'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: 'create-project.sh'
    arguments: '$(adoProjectName) $(adoOrganizationUri)'
- task: AzureCLI@2
  displayName: Azure CLI
  inputs:
    azureSubscription: 'Demo Account MSDN'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: 'create-service-connection.sh'
    arguments: '$(adoProjectName) $(adoOrganizationUri) $(resourceGroupName)'
    
